//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Агент
{
	public virtual string Имя
	{
		get;
		set;
	}

	public virtual int Кол_во_долгов
	{
		get;
		set;
	}

	public virtual int Кол_во_погашеных_долгов
	{
		get;
		set;
	}

	public virtual int ID
	{
		get;
		set;
	}

	public virtual int Номер_телефона
	{
		get;
		set;
	}

}

