//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Счёт
{
	public virtual int Баланс
	{
		get;
		set;
	}

	public virtual DateTime Дата_создания
	{
		get;
		set;
	}

	public virtual DateTime Дата_погашения
	{
		get;
		set;
	}

	public virtual int ID_должника
	{
		get;
		set;
	}

	public virtual bool Тип_счёта
	{
		get;
		set;
	}

	public virtual int Частота_платежей
	{
		get;
		set;
	}

	public virtual int Значение_платежей
	{
		get;
		set;
	}

	public virtual int ID
	{
		get;
		set;
	}

	public virtual bool Направленность
	{
		get;
		set;
	}

	public virtual void Создание_счета()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Редактирование_счёта()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Удаление_счета(int ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Просмотр_счёта(int ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Изменение_баланса(int ID, int sum)
	{
		throw new System.NotImplementedException();
	}

}

